DROP DATABASE IF EXISTS PROVEEDORES;
 CREATE DATABASE PROVEEDORES;
 USE PROVEEDORES;
 CREATE TABLE PROVEEDORES(
		 PK_PROVEEDORES INT PRIMARY KEY AUTO_INCREMENT,
		 NOMBRE VARCHAR(60) NOT NULL,
		 DIRECCION VARCHAR(100) NOT NULL,
		 CIUDAD VARCHAR(100) NOT NULL,
		 PROVINCIA VARCHAR(100) NOT NULL
 );
 CREATE TABLE CATEGORIAS(
		PK_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
		NOMBRE VARCHAR(60) NOT NULL UNIQUE
 );
  CREATE TABLE PIEZAS(
		 PK_PIEZAS INT PRIMARY KEY AUTO_INCREMENT,
		 NOMBRE VARCHAR(60) NOT NULL,
		 COLOR VARCHAR(60) NOT NULL,
		 PRECIO NUMERIC(6,2) NOT NULL CHECK (PRECIO > 0.0),
		 FK_CATEGORIA INT NOT NULL,
				FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIAS(PK_CATEGORIA)
 );
  CREATE TABLE HISTORIAL_SUMINISTROS(		
		FK_PIEZAS INT NOT NULL,
				FOREIGN KEY (FK_PIEZAS) REFERENCES PIEZAS(PK_PIEZAS),
        FK_PROVEEDORES INT NOT NULL,
				FOREIGN KEY (FK_PROVEEDORES) REFERENCES PROVEEDORES(PK_PROVEEDORES),
		FECHA DATE NOT NULL,
        CANTIDAD INT NOT NULL CHECK (CANTIDAD > 0),
        PRIMARY KEY (FK_PIEZAS, FK_PROVEEDORES, FECHA)
 );
 INSERT INTO PROVEEDORES (NOMBRE, DIRECCION, CIUDAD, PROVINCIA) VALUES
		('Proveedor1', 'Calle 123', 'Ciudad1', 'Provincia1'),
		('Proveedor2', 'Avenida 456', 'Ciudad2', 'Provincia2'),
		('Proveedor3', 'Bulevar 789', 'Ciudad3', 'Provincia3');
INSERT INTO CATEGORIAS (NOMBRE) VALUES 
		('Categoría1'),
		('Categoría2'),
		('Categoría3');
INSERT INTO PIEZAS (NOMBRE, COLOR, PRECIO, FK_CATEGORIA) VALUES 
		('Pieza1', 'Rojo', 10.50, 1),
		('Pieza2', 'Azul', 15.75, 2),
		('Pieza3', 'Verde', 20.30, 3);
INSERT INTO HISTORIAL_SUMINISTROS (FK_PIEZAS, FK_PROVEEDORES, FECHA, CANTIDAD) VALUES 
		(1, 1, '2023-10-04', 100),
		(2, 2, '2023-09-04', 150),
		(3, 3, '2023-08-04', 200);
SELECT * FROM PIEZAS



